language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=Django==1.11.5
  - DJANGO=Django==2.0a1

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=Django==2.0a1

install:
  - pip install -r requirements.txt
  - pip install -q $DJANGO
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - flake8
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
